### ISSUE TITLE
Investigate `filepath.WalkDir` to replace `fastwalk`

### ISSUE THREAD

**Issue by caitlinelfring** [get-woke/woke#107]
[`filepath.WalkDir`](https://pkg.go.dev/path/filepath@master#WalkDir) was added in go 1.16 (https://tip.golang.org/doc/go1.16#path/filepath), which does not call `os.Lstat` on every visited file or directory, which `filepath.Walk` does.

This is the reason I went with `fastwalk` (more details here: https://github.com/s12chung/fastwalk/wiki)

## Acceptance criteria

- [ ] Replace `fastwalk` with `filepath.WalkDir` in https://github.com/get-woke/woke/blob/5b45f81dc8522c436f782e3093094a1c15da9bbd/pkg/walker/walker.go#L14-L24. The same behavior should be expected
- [ ] Measure performance impact of `filepath.WalkDir` vs `fastwalk` (ie benchmark/pprof) and record results here
- [ ] Determine if `fastwalk` should be replaced

**Comment by ollien** [comment]
I've done some experiments with this:

Short answer, yes, it's slower. However, in my experience, `fastwalk` tends to miss files in what appears to be a race condition that I couldn't exactly pin down.

**Comment by cognitivegears** [comment]
Just to add in for additional consideration is that that there are serveral options that may be good to add to Woke that currently exist in ripgrep - the ability as an option to choose whether or not to traverse symbolic links, the ability to set a maximum file size to search, the option to only check files on the same filesystem, and the ability to check to see if a file is the same as the current STDOUT (not sure if this may be beneficial on some platforms). I don't believe any of these features would be possible however without switching to filepath.WalkDir (or calling Lstat from the walkFunc, which would defeat any performance increase) but could be very handy in some situations.

**Comment by cognitivegears** [comment]
Ok so I did some more testing with this and I'm pretty sure it just doesn't make a practical difference whether `woke` uses `fastwalk` or `filepath.Walk`. It looks like the time taken for regular expression rule processing is an order of magnitude greater than the directory walk, so with rules enabled even on the largest source base I could get my hands on (the linux kernel) it really added no practical difference - about 3 seconds on almost 3 minute runs. 

For smaller source bases such as the woke source the executions were sub-second in all cases, and for the in-between source base (vim) the non-fastwalk implementation actually completed faster, although this is very likely due to the fact that the difference is just lost in the noise since it is a much smaller effect compared to the rules processing. The run with all rules disabled shows the difference between the implementations .010s in this case.

For testing, I ran `woke` against three code bases - the woke source itself, the source base for vim, and the source base for the linux kernel in order to represent small, large, and huge source bases respectively. I used time to capture the results of each run, and for runs with results used the simple output and redirected output to /dev/null to limit the impact as much as possible. I ran the tests on a Core i7-10510U CPU (8 core) laptop, with 32GB memory and a 500GB m.2 NVME drive, running Pop!_OS 2021.04 (Ubuntu based distribution).

Below are the results. I am reporting on the average of 2 runs each of "wall-time" for each scenario. I have the rest of the results (system/user/cpu times and values for each run) if needed, but the results overall were consistent and close between all executions.  See below:

*** Woke with default rules enabled

|Source|Findings|Fastwalk average|Normal average|
|---------|------------|-----------------------|---------------------|
|woke|0|.044|.061|
|vim|661|7.303|7.171|
|linux|60611|2:53.155|2:57.255|


*** Woke with all rules disabled
|Source|Findings|Fastwalk average|Normal average|
|---------|-----------|------------------------|---------------------|
|woke|0|.020|0.15|
|vim|0|0.649|0.759|
|linux|0|13.827|18.529|

Based on these results, I believe that we should change the library from `fastwalk` to `filepath.Walk`. I did not test this against `filepath.WalkDir` because the usefulness of having the extra information from `filepath.Walk` I believe makes it the preferred implementation due to the additional functionality that can be gained with it (option to set a maximum filesize, option whether to follow or skip symlinks, ability to skip file created from stdout, etc.) If we wanted to look for time improvements I would suggest that we look to the regular expression processing instead to see if there are any places that could be improved there. Please let me know your thoughts.

**Comment by cognitivegears** [comment]
Note - overall I find the performance of `woke` to be pretty good for almost all cases, excepting huge source bases such as the linux kernel. At almost 3 minutes for the linux kernel (on my machine) it may not be reasonable to run `woke` for every check-in, though that is a pretty extreme case. If faster speed is desired, I think it may be a good idea to look at the file searching algorithms. Check out https://boyter.org/posts/faster-literal-string-matching-in-go/ for some options where regular expressions aren't needed (no word boundaries, etc)

**Comment by ollien** [comment]
@cognitivegears For what it's worth, Woke's usage of `fastwalk` does not actually need any information that is not provided by `WalkDir`. The only thing that is used is whether the target is a directory, which is provided by [`fs.DirEntry`](https://pkg.go.dev/io/fs#DirEntry). If more information is needed, you can always call `stat` yourself later.

https://github.com/get-woke/woke/blob/a391dc9e2fdcb7dc545b381e163b431109aa43c5/pkg/walker/walker.go#L14-L24

**Comment by caitlinelfring** [comment]
Sounds like there isn't a significant performance increase by switching, so unless there are issues with fastwalk, I'm going to table this for now. Thanks everyone for their in-depth investigation!!
