### ISSUE TITLE
Community Tools

### ISSUE THREAD

**Issue by cognitivegears** [get-woke/woke#125]
**Is your feature request related to a problem? Please describe.**
By all measures `woke` is a successful project. It is in active use by multiple companies and individuals. According to the main repository page there are over 20 contributors. Also you have done a fantastic job of quickly responding to feature requests and pull requests. I know that I would like to find additional ways to help and I'm sure there are others that feel the same way. To that end, I'd like to suggest that it would be great to add some tools for enhancing collaboration for both contributors and users.

**Describe the solution you'd like**
Some examples of tools that could be helpful:
* A collaboration tool such as Discord, IRC, Slack, Mattermost, etc
   - Bounce ideas off of other contributors, see if anyone is already working on a feature, etc
   - Place for users to post questions and get help, or collaborate on ways to implement `woke` at their companies or projects
   - Discuss ways to increase exposure of `woke`
   - Announcements
* Mailing list (notification of new releases, etc)
* Expanded getwoke.tech (roadmap, etc)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by caitlinelfring** [comment]
I enabled [GitHub Discussions](https://github.com/get-woke/woke/discussions) which is a perfect fit for this in the immediate. If woke outgrows it, I'll be happy to consider alternatives. This project has had its fair share of trolls so I plan on being cautious about it and will use my own discretion in disabling it if I need to.

I'm also working on building an official documentation website because the README is starting to get too long

Regarding a mailing list, people should "Watch" this repo to automatically get notifications when new releases are published. You can even customize which events you get notified for. I would prefer not to have to manage a separate release notification workflow when there's already one built into GitHub.

The email looks like this:
![image](https://user-images.githubusercontent.com/12818450/128648966-2fd0f8e7-1a84-41db-b3e6-f33cb74cee14.png)

**Comment by cognitivegears** [comment]
Thanks Caitlin! This sounds perfect. Really I was looking for something less formal than a new Issue for each one of my crazy ideas :) and GitHub Discussions is perfect for that. I totally understand what you are saying about trolls, I've been put down and called names before just for putting in PRs on open source repos to fix non-inclusive language. Honestly more than a little disheartening. One of the reasons I'm so happy that this project exists. Thank you.
