### ISSUE TITLE
Woke seems to miss a LOT of the Django Unchained screenplay.

### ISSUE THREAD

**Issue by TheReverend403** [get-woke/woke#84]
It's been a while since I watched it, but I'm pretty sure "slave" is the least of this screenplay's concerns.

Test file: https://dev.pste.pw/f/Ybx0P.txt

Output: https://dev.pste.pw/f/McCDL.txt

**Comment by caitlinelfring** [comment]
Can you provide more details on your bug report? What exactly is the problem you're encountering? I also suggest reading through the [README](https://github.com/get-woke/woke#readme) to understand how to customize rules if you're looking to expand past the non-default rules.

**Comment by SIX10** [comment]
Using ctrl-f in Firefox on the screenplay gives 146 instances where "slave" is used in the script. The output of woke gives 146 instances as well. Seems alright to me.

**Comment by caitlinelfring** [comment]
Woke is a tool to detect non-inclusive language in source code and provide alternatives. You can't really use woke to request that the writers of Django Unchained change their script. 

Aside from that, you can customize woke to identify any words you'd like. I invite you read the [README](https://github.com/get-woke/woke#readme) and [contributing guidelines](https://github.com/get-woke/woke/blob/main/CONTRIBUTING.md) to learn more. Since this issue isn't really related to a bug in the programming, I will be closing it.
